### ISSUE TITLE
Fullscreen Tablet/Touchscreen bug

### ISSUE THREAD

**Issue by Neogrey** [multiSnow/mcomix3#102]
System:
Debian Sid
Gnome 3.34.3-1 + Wayland
1.2.1mcomix3+git20191129-1

1. Open some manga on tablet with mcomix
2. Click on fullscreen
3. Close the fullscreen  (swipe with two fingers down)
4. Go back to fullscreen is no longer possible

This bug only occurs in tablet mode when you're closing the fullscreen with the touch gesture  (swipe with two fingers down).

After closing the fullscreen, fullscreen (Vollbild) is still selected:
![Bildschirmfoto von 2020-01-12 13-35-19](https://user-images.githubusercontent.com/10816058/72219095-6c575d80-3542-11ea-9f4f-74a3b2b3d53c.png)

Disable fullscreen and then its greyed out:
![Bildschirmfoto von 2020-01-12 13-35-35](https://user-images.githubusercontent.com/10816058/72219096-6c575d80-3542-11ea-97ae-059879cc977c.png)

**Comment by multiSnow** [comment]
Sorry, I don't have a tablet nor touch screen to test finger gesture, and mcomix does not have code to recognize gesture currently.
Below is a simple code to test (un)fullscreen and `window-state-event`.
Please run this code with `python3`, click `Fullscreen` button and swip, to see whether the text on the window changed as expected.
Thanks.

It should show both `False` at startup, `was_fullscreen:False, is_fullscreen: True` after `Fullscreen` button clicked, and change to `was_fullscreen:True, is_fullscreen: False` by that gesture.

```
from datetime import datetime

from gi import require_version
require_version('Gdk','3.0')
require_version('Gtk','3.0')
from gi.repository import Gdk,Gtk

class MainWindow(Gtk.Window):
    def __init__(self):
        super(MainWindow, self).__init__(type=Gtk.WindowType.TOPLEVEL)
        self.was_fullscreen=False
        self.connect('destroy',self.close)
        self.connect('window-state-event',self.change_state)

        layout=Gtk.Box()

        fs_button=Gtk.Button(label='Fullscreen')
        fs_button.connect('clicked',self.click_fullscreen)
        layout.add(fs_button)

        unfs_button=Gtk.Button(label='Unfullscreen')
        unfs_button.connect('clicked',self.click_unfullscreen)
        layout.add(unfs_button)

        self.label=Gtk.Label()
        self.label.set_selectable(True)
        layout.add(self.label)

        self.add(layout)

    def click_fullscreen(self,widget):
        self.fullscreen()

    def click_unfullscreen(self,widget):
        self.unfullscreen()

    def change_state(self,widget,event):
        self.label.set_text('{}: was_fullscreen:{}, is_fullscreen: {}'.format(
            datetime.now(),self.was_fullscreen,self.is_fullscreen))
        self.was_fullscreen=self.is_fullscreen

    def close(self,*args,**kwargs):
        if Gtk.main_level():
            Gtk.main_quit()

    @property
    def is_fullscreen(self):
        state=self.get_window().get_state()
        return 0!=(state&Gdk.WindowState.FULLSCREEN)

if __name__ == '__main__':
    window=MainWindow()
    window.show_all()
    try:
        Gtk.main()
    except Exception as e:
        window.destroy()
        print('close by exception:',e)
    except KeyboardInterrupt:
        window.destroy()
        print('close by Ctrl-C')
```

**Comment by Neogrey** [comment]
Thanks for the fast response. I tried to run your code and everything seems fine to me,  feel free to ask me for additional information/help.

Startup:
![Bildschirmfoto von 2020-01-14 22-06-35](https://user-images.githubusercontent.com/10816058/72382996-c14dcc00-371a-11ea-964e-44bbb8bfb59d.png)

Click on Fullscreen:
![Bildschirmfoto von 2020-01-14 22-06-43](https://user-images.githubusercontent.com/10816058/72382998-c14dcc00-371a-11ea-927b-9cffd66a3a9a.png)

Closing with touch gesture:
![Bildschirmfoto von 2020-01-14 22-06-48](https://user-images.githubusercontent.com/10816058/72382999-c14dcc00-371a-11ea-834b-77afc12d948d.png)

**Comment by multiSnow** [comment]
Please test #104 to see whether the `Fullscreen` action shows as expected with gesture.
Thanks.

**Comment by Neogrey** [comment]
With #104:
After closing the fullscreen mode, it's still selected under "View". But after re-enable the fullscreen option, the fullscreen is back (so it's no longer greyed out).

Maybe it would be possible to disable automatically  the fullscreen option under "View" after closing the fullscreen mode with touch gesture ?

**Comment by multiSnow** [comment]
#104 has been updated. Please test to see the (un)fullscreen action works as expected.

**Comment by Neogrey** [comment]
Works fine now, thanks a lot for the fast fix.
