### ISSUE TITLE
Cannot display more than 500 covers in library

### ISSUE THREAD

**Issue by emfox** [multiSnow/mcomix3#105]
https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=945493

And I can confirm that too if you have more than 500 comic books in your library, the 501(or 502?) book cover and further will be display as blank, even in today's new build, which I just uploaded into Debian.

**Comment by multiSnow** [comment]
~~Yes, there is a hard limit on it.
See comment in `mcomix.library.pixbuf_cache.get_pixbuf_cache` (and in mcomix-py2 https://sourceforge.net/p/mcomix/git/ci/master/tree/mcomix/library/pixbuf_cache.py#l63)~~

Edit:
这块代码我之前没动过也没细看，这次看了一下，设计上应该是增加新缓存前弹出旧缓存，但是弹出旧缓存的线程锁放在了增加新缓存的线程锁里面，所以这就是个死锁bug。
线程锁的问题会有点烦，等春节放假了我仔细搞。

**Comment by emfox** [comment]
ok, so could we for example add a prefs setting that let user decide how many covers at most shall display, if this cannot be fixed gracefully?

**Comment by multiSnow** [comment]
I will gracefully fix this issue before the end of CNY.
Please be patient.
Thanks.

**Comment by multiSnow** [comment]
@emfox BTW, `libunrar5` should be used instead of `libunrar` in the `Suggests` section of deb.
And, https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=943642 should be already fixed by https://github.com/multiSnow/mcomix3/commit/557d764b15dbc7c495ead18038778401f4450366.

**Comment by emfox** [comment]
thanks, I will fix it next upload.
