### ISSUE TITLE
[Feat. Req.] .webp image support. 

### ISSUE THREAD

**Issue by momoe** [multiSnow/mcomix3#11]
https://developers.google.com/speed/webp/ 

Submitting a ticket to get webp support. with HD or +4k comic files being more common now, this lossless compression format is being considered as a great lossless compression option. 

Even with level 9 png compression with a grayscale 8bpc profile, webp lossless was 20% more efficient in my tests.

Please consider adding support for this in the future.

**Comment by multiSnow** [comment]
webp should be already supported by pillow 2.0.0 and above ( see: https://github.com/python-pillow/Pillow/blob/master/CHANGES.rst#200-2013-03-15 ).
mcomix3 prefers pillow to gdk-pixbuf as image loader, so if a pillow built with webp support, it should work fine with webp image.
Also, a webp plugin for gdk-pixbuf is available ( see: https://github.com/aruiz/webp-pixbuf-loader ), but is not tested.
