### ISSUE TITLE
slideshow fails silently until application is closed

### ISSUE THREAD

**Issue by andykais** [multiSnow/mcomix3#111]
the slideshow scrolls down the page but does not advance to the next page. No errors are shown, but when I quit the application I get this stack trace:
```
Traceback (most recent call last):
  File "/usr/share/mcomix/mcomix/main.py", line 1112, in close_program
    self.terminate_program()
  File "/usr/share/mcomix/mcomix/main.py", line 1149, in terminate_program
    self.slideshow.stop()
  File "/usr/share/mcomix/mcomix/slideshow.py", line 29, in stop
    self._window.update_title()
  File "/usr/share/mcomix/mcomix/main.py", line 1003, in update_title
    self.imagehandler.get_pretty_current_filename()]
  File "/usr/share/mcomix/mcomix/image_handler.py", line 360, in get_pretty_cu
    img_file = os.path.abspath(self.get_current_path())
  File "/usr/share/mcomix/mcomix/image_handler.py", line 165, in get_current_p
    return self._image_files[self._current_image_index]
TypeError: list indices must be integers or slices, not NoneType
```

**Comment by multiSnow** [comment]
https://github.com/multiSnow/mcomix3/tree/fix-slideshow try to fix this issue, please test, thanks.

**Comment by andykais** [comment]
Hi, I cloned and ran from the `fix-slideshow` branch. The error has gone away, but the slideshow still does not advance. When I quit no error logs are shown. Page scrolling still happens when the slideshow starts

**Comment by multiSnow** [comment]
It seems to be so designed.
The flipping behavior also abides by the value of `Behavior -> Scroll -> 'Number of "steps" to take before flipping the page'` option, means that page only flipped in scrolling after the steps of that value.

**Comment by andykais** [comment]
Ah, I see. I was able to get this working after some debugging. I had "Flip pages when scrolling off the edges of the page" disabled. This was intentional though. I purposefully disabled this setting because I prefer manually changing the page with PageUp, PageDown.

I do not know why someone would care about the steps before flipping a page during a slideshow. I imagine they would simply want it to advance after it reaches the bottom. If they wanted a longer pause between pages, they could just set the slideshow delay higher. If a pr is welcome, I could take a crack at special-casing slideshow steps
