### ISSUE TITLE
7z whithout p7zip-rar, doesn't completly fail

### ISSUE THREAD

**Issue by ghost** [multiSnow/mcomix3#114]
Don't have rar, unrar and unrar-free installed.
Only unar.

mcomix will not extract all images. For a particular archive, it's always the same images that don't get extracted. I don't see a pattern.

the command "unar" seams to work fine in the terminal and in the archive manager.

tested in ubuntu 20.04
(unar is installed by default and works decently, so it's not a small bug)

**Comment by multiSnow** [comment]
`unar` command is not supported and used by mcomix.
mcomix uses libunrar, `unrar` command or `7z` command to deal with 'rar' archive.
For ubuntu, please install [libunrar5](https://packages.ubuntu.com/focal/libunrar5) or [unrar](https://packages.ubuntu.com/focal/unrar) or [p7zip-rar](https://packages.ubuntu.com/focal/p7zip-rar).

Even the `unar` (or any other command) could correctly handle rar format, it does not mean that mcomix could use it to extract a archive.
To use external command, mcomix needs to analyse the output of every command. It is what the `mcomix/archive/*_external.py` modules do.

mcomix does not have magic to play with a unknown external command.

**Comment by ghost** [comment]
yea, i already know what to install...

What actually is happening is stranger. 7z can half work with out any unrar thing. I mean nothing, no libs or unrar variants, or p7zip-rar. Just nothing.... It doesn't just fail 100%, it actually extracts some of the files and the rest are empty files.

So it was using bare 7z, not unar. The archive manager was using unar. Now that i think about it, this must be the second time that this thing confuses me.

I would propose, that mcomix tests if 7z is unrar capable for real.

**Comment by multiSnow** [comment]
Please test https://github.com/multiSnow/mcomix3/tree/p7zip-rar5-test and see whether it works as desired, thanks.

**Comment by ghost** [comment]
it was supposed to refuse  opening them?
It still opens them.

I have v4 rar files (as claimed from "file").
You took v4 in to account?

also, the path in ubuntu is "/usr/lib/p7zip/Codecs/Rar.so"
So, if the Codec wasn't included, it would have failed anyway.

**Comment by multiSnow** [comment]
https://github.com/multiSnow/mcomix3/tree/p7zip-rar5-test is updated and p7zip will be completely disabled for rar archive without p7zip-rar, no matter rar4 or rar5.

**Comment by ghost** [comment]
.... still opens them :/

**Comment by multiSnow** [comment]
fixed with https://github.com/multiSnow/mcomix3/commit/aa96a714c09372acf68342c02d7f963af11fe9fe
