### ISSUE TITLE
F to exit full screen

### ISSUE THREAD

**Issue by propri** [multiSnow/mcomix3#124]
Full screen can be entered with `F`, but not exited.

**Comment by multiSnow** [comment]
You could see three shortcuts about fullscreen in preferences: 'Fullscreen', 'Exit from fullscreen' and 'Toggle fullscreen'.
If you want to use same key to both enter and exit fullscreen, please use 'Toggle fullscreen'.

**Comment by multiSnow** [comment]
You could see three shortcuts about fullscreen in preferences: 'Fullscreen', 'Exit from fullscreen' and 'Toggle fullscreen'.
If you want to use same key to both enter and exit fullscreen, please use 'Toggle fullscreen'.

**Comment by multiSnow** [comment]
You could see three shortcuts about fullscreen in preferences: 'Fullscreen', 'Exit from fullscreen' and 'Toggle fullscreen'.
If you want to use same key to both enter and exit fullscreen, please use 'Toggle fullscreen'.

**Comment by multiSnow** [comment]
You could see three shortcuts about fullscreen in preferences: 'Fullscreen', 'Exit from fullscreen' and 'Toggle fullscreen'.
If you want to use same key to both enter and exit fullscreen, please use 'Toggle fullscreen'.

**Comment by multiSnow** [comment]
You could see three shortcuts about fullscreen in preferences: 'Fullscreen', 'Exit from fullscreen' and 'Toggle fullscreen'.
If you want to use same key to both enter and exit fullscreen, please use 'Toggle fullscreen'.

**Comment by multiSnow** [comment]
You could see three shortcuts about fullscreen in preferences: 'Fullscreen', 'Exit from fullscreen' and 'Toggle fullscreen'.
If you want to use same key to both enter and exit fullscreen, please use 'Toggle fullscreen'.
