### ISSUE TITLE
[GTK bug]drag and drop books from one library to the other doesn't work

### ISSUE THREAD

**Issue by ghost** [multiSnow/mcomix3#15]
This is a bug in GTK. drag and drop books from one library to the other doesn't work.

https://gitlab.gnome.org/GNOME/pygobject/issues/104

https://github.com/exaile/exaile/issues/200

https://github.com/jaap-karssenberg/zim-desktop-wiki/issues/390

tmp work around

**Comment by multiSnow** [comment]
PR merged.
