### ISSUE TITLE
Future: Support jxl (JpegXL)

### ISSUE THREAD

**Issue by brunoais** [multiSnow/mcomix3#164]
It's still early to actually implement this. I'd wait for the browsers to do it first or, at least, wait a short while.
However, I think it's worthwhile to make an issue so the matter is handled eventually.

Link to the library: https://github.com/libjxl/libjxl
Firefox status on it: https://bugzilla.mozilla.org/show_bug.cgi?id=1539075

**Comment by multiSnow** [comment]
Any image format support is provided by PIL, with GdkPixbuf as fallback.
Please create feature request to them instead of here.
This issue, and any further issue like this, will be closed without fixing.
