### ISSUE TITLE
[INFO] some pdf files don't work

### ISSUE THREAD

**Issue by ghost** [multiSnow/mcomix3#24]
EDIT: This bug is fixed in mutool 1.14

for example this one.
https://www.gwern.net/docs/iq/2017-flynn.pdf

works fine with mupdf
In mcomix a lot of this message
```
error: Cannot convert between incompatible pixmaps
warning: Ignoring error during interpretation
```

**Comment by chelovechishko** [comment]
I have 
> page 2017-flynn.pdf 1mutool: source/fitz/colorspace.c:1399: fast_rgb_to_cmyk: Assertion `"This should never happen" == NULL' failed.

with `mutool draw -c rgb 2017-flynn.pdf` i get the same message. mupdf opened it too. It's mupdf-1.12.0 though. In the current git master code, i don't see this assertion anymore.

**Comment by ghost** [comment]
Yep, it doesn't work in mutool despite working in mupdf. Bug in mutool.

**Comment by multiSnow** [comment]
upstream fixed.
