### ISSUE TITLE
you are taking too long

### ISSUE THREAD

**Issue by ghost** [multiSnow/mcomix3#61]
Dear @multiSnow you are taking too long. -_-
Could you just give me commit rights?

I plan on merging my stuff, then show the result to ark and have the official repo relocate here...
I prefer avoiding creating yet an other forked repo, it's confusing enough as it is.

**Comment by emfox** [comment]
Hello, I am the Debian packager for mcomix.
Could I ask what's the status of mcomix python3 ports now, is it stable for daily use?
Since debian is now dropping support for python2, we are considering a switch.
Isthis repository the official mcomix upstream now?

**Comment by multiSnow** [comment]
It is not official of mcomix. The official should always be https://sourceforge.net/projects/mcomix/ .
I am using it daily in debian sid, but some of dependences is built by myself.
So, maybe, you need to check the compatibility, especially Pillow.
It is not installed in `/usr/lib/python3`, but in `/usr/share`, similar to [terminator](https://packages.debian.org/sid/all/terminator) .

Some hints for debian package:
```
Depends: gir1.2-gtk-3.0,
         python3-gi,
         python3-pil,
Recommends: python3-chardet,
Suggests: unrar | libunrar,
          p7zip,
```
```
override_dh_auto_install:
	python3 installer.py --srcdir=mcomix --target=debian/tmp/usr/share
```
```
$>> cat debian/mcomix.install 
/usr/share/mcomix
```
```
$>> cat /usr/bin/mcomix 
#!/bin/sh
python3 /usr/share/mcomix/mcomixstarter.py "$@"
exit $?
```

I also build libflif by my self for FLIF format support, but I suggest you to ignore it. libflif is not stable enough.

**Comment by ghost** [comment]
I'm using it on ubuntu 18.04 . It's fine.

The open issues you see are a bit misleading. It's stable and ok for everyday use.

Now about whats upstream.... The only official developer is ark on source forge, and he has no time....

**Comment by emfox** [comment]
@multiSnow @pirate486743186 thanks for the info, so I think I'll wait a few months more to see if there's new progress of official python3 support. And I'll keep an eye on this repo.
