### ISSUE TITLE
memo about portable mode

### ISSUE THREAD

**Issue by multiSnow** [multiSnow/mcomix3#63]
1. `library.db`, `lastreadpage.db`, `bookmarks.pickle` and `file.pickle` store absolue path. 
But in portable mode, how to make sure the saved path is still there?
Using relative could not completely solve this problem since path may changed if it is out of mount point (*nix) or in another drive (win32)
One idea is only adding path under the same mount point where mcomix3 placed in.
That means, for example, books out of usb stick could not be added to library (yes, it is not in your 'usb stick library').
It could be done by using `os.path.ismount`, under both *nix and win32.
And, maybe, data and preference should be marked as not compatible without portable mode.

2. Especially for using under win32, is it also necessary to store depended library and tools along with mcomix3?
If so, maybe another script is needed to download and place them, and let mcomix3 to known it.
But it seems that gtk3 do not provide pre-compiled binary for win32, and developer needs to build everything using msys2.
It makes things too complex.
I hate win32 :)

Work about portable mode is doing in https://github.com/multiSnow/mcomix3/tree/portable-mode , and will be merge to main branch once all work done.

**Comment by ghost** [comment]
1.Well, yes, they are limits. The user should exercise some common sense. I didn't want to make it too complicated either, but i guess it will accumulate more features over time.

If a book doesn't exist anymore, the library doesn't care. You could have local books on the computer, that show up in your library. So maybe not restrict that. The user could get a warning though.

2.That's a question of packaging, not really about coding. Even on linux, do you pack everything in an appimage? 32bit compatible? ARM compatible? That's up to downstream to decide what it wants.

3. No need to be "feature complete". Merge it if it functions reasonably well. Right now, fixing the user facing bugs is more important.

**Comment by multiSnow** [comment]
1. I make it as a portable-mode only option. Let user to choose what they want.

2. OK, let's forget it. I really do not want to touch win32, especially development.

**Comment by ghost** [comment]
Don't force your self in rewriting my sloppy new features.
They where meant to be simple stubs.
