### ISSUE TITLE
memo about encrypted archive in library

### ISSUE THREAD

**Issue by multiSnow** [multiSnow/mcomix3#68]
If an archive is encrypted with password, files stored in it should never be available in anyway without password.
So, no **real** thumbnail of encrypted archive should be appeared in library, even if it is only a thumbnail.

1. Add a keyword argument to all `archive.extract` that make it do nothing if archive is encrypted. It would be better to check whether archive is encrypted before extract it, but it seems not easy to do with `RarArchive` provided by libunrar.so/unrar.dll.
2. If archive is encrypted (by checking the return value of `archive.extract`, or some attribute of `archive`), using a special icon as thumbnail (e.g. a lock) in library.

All above should only involve the thumbnail creator.

( I have to learn about `ctypes`, also get some normal encrypted and header encrypted rar files as example. Rar file could be created only by winrar, that means I have to setup a windows. It is terrible. I want to give up :( )

Edit:
3. Adding a encrypted archive to library does not needs password. Library should show an encrypted archive having 0 pages.
4. If an archive is not encrypted but the sub-archive is encrypted, skip it silently.

**Comment by ghost** [comment]
you mean these files in the git repo???
mcomix3/test/files/archives/Encrypted.rar
mcomix3/test/files/archives/EncryptedHeader.rar

yes, ctypes, not a trivial change, and the functions use multiple inheritance .
