### ISSUE TITLE
background color in library

### ISSUE THREAD

**Issue by ghost** [multiSnow/mcomix3#78]
@multiSnow 
The background color of the library, used to be black. Now it's just the color of the theme, with no possibility of changing it...

**Comment by multiSnow** [comment]
Yes, it is using theme color, and we already did a preference to let users choose a theme they preferred.

**Comment by ghost** [comment]
-_- ....

It has always been black regardless of theme....
With the main window, you can change it's color in the settings. So that's not a big deal.
If you want to have black in the library, you have to rebuilt a new theme.... beh :/

Maybe, use the same background color setting as with the main window?

**Comment by multiSnow** [comment]
No.
There's no needed for users (and us) to build any theme.
Just take one from https://www.gnome-look.org/browse/cat/135/ .
