### ISSUE TITLE
Can't display pictures without file ending

### ISSUE THREAD

**Issue by sevu** [multiSnow/mcomix3#80]
Hello again.

I noticed that mcomix detects images without file names as folders, and concludes that there are no images in this folder.
Similarly, the same happens if I name the extension arbitary.

(In this case, it's the picture of the day used as plasma wallpaper, probably because plasma doesn't know in advance what format the image will be)
Unrelated to recent merge

**Comment by multiSnow** [comment]
Hello.
If you mean only files with a vailed extension for image type is recognized, yes, it is so designed.
Mcomix recognizes image files by file name, not 'magic number', to avoid reading starting bytes of every file, especially that is 'solidly' compressed in archive, for a good preformance.

But it is not a bad idea to support 'magic number'. Maybe I would consider making it optional.

**Comment by multiSnow** [comment]
Please check #83 to see whether it is what you desired, starting at Preferences -> Advanced -> Detect image file(s) by mimetypes.
