### ISSUE TITLE
Flatpak / Snap / AppImage Package

### ISSUE THREAD

**Issue by DesertStars** [multiSnow/mcomix3#91]
Self-explanatory, as it stands now mcomix3 doesn't really provide an easy way for regular users to install it, unless it's in their package manager.

**Comment by wyatt8740** [comment]
mkdir -p ~/bin
    python3 ./installer.py --target ~/bin
    ln -s ~/bin/mcomix/mcomixstarter.py ~/bin/mcomix3

Add to `~/.bashrc` (and maybe `~/.profile`), if it doesn't already contain it:

    if [ -d "$HOME/bin" ] ; then
        PATH="$HOME/bin:""$PATH"
    fi

run with:

    mcomix3

Seems to me like Flatpak/Snap/AppImage are all unnecessarily complex overhead.

**Comment by xinyazhang** [comment]
Since mcomix is a python application requiring no custom C/C++ module, a pip wheel is probably more preferred than flatpak.
