### ISSUE TITLE
Use Meson build system

### ISSUE THREAD

**Issue by worldofpeace** [multiSnow/mcomix3#96]
Quoting @multiSnow here
> There's really no need to build or install, and setup.py does not help to correctly resolve the dependences of mcomix3 (and maybe any python program depends on pygi and gtk3).
> For packaging, simply treat anything in mcomix/ as data files, and call mcomix/mcomixstarter.py with the interpreter.

For Applications that use pygi and gtk3, it has become popular to use the Meson build system
* https://gitlab.gnome.org/GNOME/gnome-music
* https://gitlab.gnome.org/World/lollypop

Surpassing some of  the drawbacks mentioned with the setup.py is that it can actually check if the required dependencies like:
* gobject-introspection
* glib
* cairo
* gdk-pixbuf

are installed via [`dependency()`](https://mesonbuild.com/Reference-manual.html#dependency).

It also has the [`python module`](https://mesonbuild.com/Python-module.html) which in 0.51.0 can take a list of module names that a python installation must have.

[`man pages`](https://mesonbuild.com/Reference-manual.html#install_man) are easy as well.

I believe this would be the most convenient option for distro packagers as well.

@multiSnow Would you accept a contribution like this?

**Comment by worldofpeace** [comment]
Forgot to mention we you could enforce the version constraints in
* https://github.com/multiSnow/mcomix3#required

so that it would fail to install if not satisfied.

**Comment by AndersonTorres** [comment]
Meson? Isn't meson a bit huge for something small as a comic reader? I would recomend waf for small softwares like that.

**Comment by worldofpeace** [comment]
I've translated some comments here and this isn't the correct place for such a discussion.
We should take to upstream, and probably once they integrate this code in mainline.

**Comment by worldofpeace** [comment]
> Meson? Isn't meson a bit huge for something small as a comic reader? I would recomend waf for small softwares like that.

As stated, for gobject-introspection using programs (a small gui), the community has really rallied behind meson as an option.

**Comment by emfox** [comment]
> I've translated some comments here and this isn't the correct place for such a discussion.
> We should take to upstream, and probably once they integrate this code in mainline.

upstream is pretty much dead, and they have no plan to migrate or support python3 gtk because of ms windows is a priority.
